# Generated by Django 3.2 on 2021-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cp', 'computers'), ('MB', 'mobiles'), ('TB', 'Tablettes')], default='CP', max_length=2),
            preserve_default=False,
        ),
    ]
