# Generated by Django 3.2 on 2021-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Gaming', 'primary'), ('photofraphie', 'secondary'), ('normal', 'danger'), ('low caost', 'warning')], default='normal', max_length=15),
            preserve_default=False,
        ),
    ]
