# Generated by Django 3.2 on 2021-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('primary', 'Gaming'), ('secondary', 'Photofraphie'), ('danger', 'Normal'), ('warning', 'Low Caost')], max_length=15),
        ),
    ]
