# Generated by Django 3.2 on 2021-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210504_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discout_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
