# Generated by Django 3.2 on 2021-05-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_discout_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quatity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
