# Generated by Django 3.2 on 2021-05-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20210505_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
