# Generated by Django 3.2 on 2021-05-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persons', 'verbose_name_plural': 'persons'},
        ),
    ]
